### ISSUE TITLE
Compatibility with Angular

### ISSUE THREAD

**Issue by amitchavan90** [jshemas/openGraphScraperLite#2]
Hello,

Can I use this lib in Angular? If yes, any leads on how to implement.

Thanks.

**Comment by jshemas** [comment]
I'm not sure how well this will work with Angular, here is an example of how to use this lib with vue: https://github.com/jshemas/vue-opengraph

You might run into some CORS issues like this -> https://github.com/jshemas/openGraphScraper/issues/102

**Comment by jshemas** [comment]
This library no longer does HTTP requests, it will now just pull Open Graph and Twitter Card info from HTML pass into it. Please open a new issue if you are still having problems.
