### ISSUE TITLE
"Time out error" and "response.buffer is not a function"

### ISSUE THREAD

**Issue by jungsunwoung** [jshemas/openGraphScraperLite#4]
![image](https://user-images.githubusercontent.com/51280827/117622693-e0912800-b1ad-11eb-98c2-8554e5c31845.png)

This is my code and I got two error

When I didn't set timeout option, I got response.buffer error
![image](https://user-images.githubusercontent.com/51280827/117622563-b2134d00-b1ad-11eb-98b3-6d58d6b6aae6.png)

and When I set timeout as an option I got time out error

![image](https://user-images.githubusercontent.com/51280827/117622510-a58ef480-b1ad-11eb-8c5a-795ff4d6224b.png)
How can I solve this problem?

**Comment by josh-manton** [comment]
I have the same error. Could it be related to Node 16?

**Comment by jshemas** [comment]
This library no longer does HTTP requests, it will now just pull Open Graph and Twitter Card info from HTML pass into it. Please open a new issue if you are still having problems.
