### ISSUE TITLE
TypeError: undefined has no properties

### ISSUE THREAD

**Issue by stanley90** [jshemas/openGraphScraperLite#5]
Hi
I'm trying to use this library, but can't make it work. I installed it via `npm`, then had to add
`exclude: new RegExp('node_modules/(?!(open-graph-scraper-lite|ky))')` to webpack.config.js babel-loader (otherwise it reported a syntax error). With this configuration it compiles, however the request fails with this:

![image](https://user-images.githubusercontent.com/48182/119009894-dd5b2080-b993-11eb-8516-6d04c8be2581.png)

The affected line seems to be https://github.com/jshemas/openGraphScraperLite/blob/master/lib/utils.js#L26
I suspect this has something to do with how it's transpiled, but I don't know how to fix it.

**Comment by optimistic-updt** [comment]
similar issue here

**Comment by jshemas** [comment]
This library no longer does HTTP requests, it will now just pull Open Graph and Twitter Card info from HTML pass into it. Please open a new issue if you are still having problems.
