### ISSUE TITLE
Open Graph Scraper Lite is for the browser, which means we want ES6 imports

### ISSUE THREAD

**Issue by geoidesic** [jshemas/openGraphScraperLite#6]
Is this possible?

**Comment by wobsoriano** [comment]
You can do some adjustments, but you'll eventually end with cors issues. It's always meant to be used outside a browser.

**Comment by jshemas** [comment]
This library no longer does HTTP requests, it will now just pull Open Graph and Twitter Card info from HTML pass into it. Please open a new issue if you are still having problems.
