### ISSUE TITLE
Typescript: "no declaration file for module"

### ISSUE THREAD

**Issue by diegoulloao** [jshemas/openGraphScraperLite#8]
I'm trying to use this library in react. with typescript but I'm having a "no declaration file for module" error as attached in the image.

I tried to install `@types/open-graph-scraper-lite` but it doesn't exist.

Any solution for this?

![Captura de Pantalla](https://user-images.githubusercontent.com/45423661/132412621-fa909bbb-1a87-49fb-b714-11db33cd5ceb.png)

**Comment by jshemas** [comment]
This library no longer does HTTP requests, it will now just pull Open Graph and Twitter Card info from HTML pass into it. Please open a new issue if you are still having problems.
